- name: Update the APT cache and install kubeadm dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    update_cache: true

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubeadm_kubernetes_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: "0644"

- name: Convert Kubernetes GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.template:
    src: kubernetes.list.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: "0644"

- name: Update the APT cache and install kubeadm
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: true

- name: Hold kubelet, kubeadm and kubectl versions
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
